export const ALL_INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

export const NON_SLEEPER_SEARCH_KEYWORDS = [
  'Stage Carriage Bus Service',
  'Private Roadways Bus Service',
  'Intercity Seater Bus Operator',
  'District Passenger Bus Operator',
  'Ordinary Bus Transport Office',
  'Route Mini Bus Service',
  'Private ISBT Bus Booking Counter',
  'State Permit Bus Fleet Operator',
  'Intercity Route Bus Stand',
  'Seater Passenger Bus Service',
  'Bus Transport Agent Office',
  'Express Stage Carriage Bus',
  'Interstate Bus Syndicate',
  'Intercity Bus Service Counter',
  'Deluxe Bus Booking Office',
];
