import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { startOfDay, startOfWeek, startOfMonth, subDays, format } from 'date-fns';

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const userRole = searchParams.get('role') || 'ADMIN';
    const userEmail = searchParams.get('email');

    // Build filter based on active role view
    let leadFilter: any = {};
    if (userRole !== 'ADMIN' && userEmail && userEmail !== 'admin@apnibus.in') {
      const user = await prisma.user.findUnique({ where: { email: userEmail } });
      if (user) {
        leadFilter.assignedToId = user.id;
      }
    }

    const allLeads = await prisma.lead.findMany({
      where: leadFilter,
      include: {
        assignedTo: {
          select: { id: true, name: true, empId: true },
        },
      },
    });

    const now = new Date();
    const todayStart = startOfDay(now);
    const weekStart = startOfWeek(now);
    const monthStart = startOfMonth(now);

    // KPI Counters
    const totalLeads = allLeads.length;
    const newLeads = allLeads.filter((l) => l.status === 'New').length;
    const hotLeads = allLeads.filter((l) => l.leadTemperature === 'HOT').length;
    const warmLeads = allLeads.filter((l) => l.leadTemperature === 'WARM').length;
    const coldLeads = allLeads.filter((l) => l.leadTemperature === 'COLD').length;
    const unassignedLeads = allLeads.filter((l) => !l.assignedToId).length;
    const assignedLeads = allLeads.filter((l) => l.assignedToId).length;

    const contactedLeads = allLeads.filter((l) =>
      ['Contacted', 'Interested', 'Follow-up', 'Demo Scheduled', 'Demo Completed', 'Converted'].includes(l.status)
    ).length;
    const interestedLeads = allLeads.filter((l) =>
      ['Interested', 'Demo Scheduled', 'Demo Completed', 'Converted'].includes(l.status)
    ).length;
    const demoScheduled = allLeads.filter((l) => l.status === 'Demo Scheduled').length;
    const demoCompleted = allLeads.filter((l) =>
      ['Demo Completed', 'Converted'].includes(l.status)
    ).length;
    const converted = allLeads.filter((l) => l.status === 'Converted').length;
    const lost = allLeads.filter((l) => ['Lost', 'Not Interested', 'Invalid'].includes(l.status)).length;

    const todaysNewLeads = allLeads.filter((l) => new Date(l.createdAt) >= todayStart).length;
    const thisWeeksLeads = allLeads.filter((l) => new Date(l.createdAt) >= weekStart).length;
    const thisMonthsLeads = allLeads.filter((l) => new Date(l.createdAt) >= monthStart).length;

    // Rates
    const contactRate = totalLeads > 0 ? ((contactedLeads / totalLeads) * 100).toFixed(1) : '0';
    const interestedRate = contactedLeads > 0 ? ((interestedLeads / contactedLeads) * 100).toFixed(1) : '0';
    const demoRate = interestedLeads > 0 ? ((demoScheduled / interestedLeads) * 100).toFixed(1) : '0';
    const conversionRate = totalLeads > 0 ? ((converted / totalLeads) * 100).toFixed(1) : '0';

    // Chart 1: Leads generated by day (last 14 days)
    const last14DaysData = [];
    for (let i = 13; i >= 0; i--) {
      const d = subDays(now, i);
      const dayStr = format(d, 'MMM dd');
      const dStart = startOfDay(d);
      const dEnd = new Date(dStart.getTime() + 86400000);
      const count = allLeads.filter(
        (l) => new Date(l.createdAt) >= dStart && new Date(l.createdAt) < dEnd
      ).length;
      last14DaysData.push({ day: dayStr, count });
    }

    // Chart 2: Leads by state
    const stateMap: Record<string, number> = {};
    allLeads.forEach((l) => {
      stateMap[l.state] = (stateMap[l.state] || 0) + 1;
    });
    const leadsByState = Object.entries(stateMap).map(([state, count]) => ({ state, count }));

    // Chart 3: Leads by temperature
    const leadsByTemperature = [
      { temperature: 'HOT', count: hotLeads },
      { temperature: 'WARM', count: warmLeads },
      { temperature: 'COLD', count: coldLeads },
    ];

    // Chart 4: Leads by status
    const statusMap: Record<string, number> = {};
    allLeads.forEach((l) => {
      statusMap[l.status] = (statusMap[l.status] || 0) + 1;
    });
    const leadsByStatus = Object.entries(statusMap).map(([status, count]) => ({ status, count }));

    // Chart 5: Leads by city
    const cityMap: Record<string, number> = {};
    allLeads.forEach((l) => {
      cityMap[l.city] = (cityMap[l.city] || 0) + 1;
    });
    const leadsByCity = Object.entries(cityMap).map(([city, count]) => ({ city, count }));

    // Chart 6: Status Funnel
    const statusFunnel = [
      { stage: 'New', count: newLeads },
      { stage: 'Contacted', count: contactedLeads },
      { stage: 'Interested', count: interestedLeads },
      { stage: 'Demo Scheduled', count: demoScheduled },
      { stage: 'Demo Completed', count: demoCompleted },
      { stage: 'Converted', count: converted },
    ];

    // Chart 7: FOS Performance Metrics
    const fosMap: Record<string, { total: number; converted: number }> = {};
    allLeads.forEach((l) => {
      const fosName = l.assignedTo ? l.assignedTo.name : 'Unassigned';
      if (!fosMap[fosName]) {
        fosMap[fosName] = { total: 0, converted: 0 };
      }
      fosMap[fosName].total += 1;
      if (l.status === 'Converted') {
        fosMap[fosName].converted += 1;
      }
    });

    const leadsByFos = Object.entries(fosMap).map(([name, data]) => ({
      name,
      count: data.total,
      converted: data.converted,
      conversionRate: data.total > 0 ? Number(((data.converted / data.total) * 100).toFixed(1)) : 0,
    }));

    return NextResponse.json({
      kpis: {
        totalLeads,
        newLeads,
        hotLeads,
        warmLeads,
        coldLeads,
        unassignedLeads,
        assignedLeads,
        contactedLeads,
        interestedLeads,
        demoScheduled,
        demoCompleted,
        converted,
        lost,
        todaysNewLeads,
        thisWeeksLeads,
        thisMonthsLeads,
        contactRate,
        interestedRate,
        demoRate,
        conversionRate,
      },
      charts: {
        last14DaysData,
        leadsByState,
        leadsByTemperature,
        leadsByStatus,
        leadsByCity,
        statusFunnel,
        leadsByFos,
        fosLeadsData: leadsByFos,
      },
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
