import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { startOfDay, startOfWeek, startOfMonth, subDays, format } from 'date-fns';

const ADMIN_EMAILS = [
  'gaurav.thakur@apnibus.com',
  'arvind.ranjan@apnibus.com',
  'admin@apnibus.in',
];

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const userRole = searchParams.get('role') || 'ADMIN';
    const userEmail = searchParams.get('email');

    const isAdmin =
      userRole === 'ADMIN' ||
      userRole === 'SUPER_ADMIN' ||
      (userEmail && ADMIN_EMAILS.includes(userEmail.toLowerCase()));

    // Build filter based on active role view
    let leadFilter: any = {};
    if (!isAdmin && userEmail) {
      const user = await prisma.user.findUnique({ where: { email: userEmail } });
      if (user) {
        leadFilter.assignedToId = user.id;
      }
    }

    const allLeads = await prisma.lead.findMany({
      where: leadFilter,
      include: {
        assignedTo: {
          select: { id: true, name: true, empId: true },
        },
      },
    });

    const now = new Date();
    const todayStart = startOfDay(now);
    const weekStart = startOfWeek(now);
    const monthStart = startOfMonth(now);

    // KPI Counters
    const totalLeads = allLeads.length;
    const newLeads = allLeads.filter((l) => l.status === 'New').length;
    const hotLeads = allLeads.filter((l) => l.leadTemperature === 'HOT').length;
    const warmLeads = allLeads.filter((l) => l.leadTemperature === 'WARM').length;
    const coldLeads = allLeads.filter((l) => l.leadTemperature === 'COLD').length;
    const unassignedLeads = allLeads.filter((l) => !l.assignedToId).length;
    const assignedLeads = allLeads.filter((l) => l.assignedToId).length;

    const contactedLeads = allLeads.filter((l) =>
      ['Contacted', 'Interested', 'Follow-up', 'Demo Scheduled', 'Demo Completed', 'Sale Done', 'Converted'].includes(l.status)
    ).length;
    const interestedLeads = allLeads.filter((l) =>
      ['Interested', 'Demo Scheduled', 'Demo Completed', 'Sale Done', 'Converted'].includes(l.status)
    ).length;
    const demoScheduled = allLeads.filter((l) => l.status === 'Demo Scheduled').length;
    const demoCompleted = allLeads.filter((l) =>
      ['Demo Completed', 'Sale Done', 'Converted'].includes(l.status)
    ).length;
    const converted = allLeads.filter((l) => ['Sale Done', 'Converted'].includes(l.status)).length;
    const lost = allLeads.filter((l) => ['Lost', 'Not Interested', 'Invalid'].includes(l.status)).length;

    const todaysNewLeads = allLeads.filter((l) => new Date(l.createdAt) >= todayStart).length;
    const thisWeeksLeads = allLeads.filter((l) => new Date(l.createdAt) >= weekStart).length;
    const thisMonthsLeads = allLeads.filter((l) => new Date(l.createdAt) >= monthStart).length;

    // Rates
    const contactRate = totalLeads > 0 ? ((contactedLeads / totalLeads) * 100).toFixed(1) : '0';
    const interestedRate = contactedLeads > 0 ? ((interestedLeads / contactedLeads) * 100).toFixed(1) : '0';
    const demoRate = interestedLeads > 0 ? ((demoScheduled / interestedLeads) * 100).toFixed(1) : '0';
    const conversionRate = totalLeads > 0 ? ((converted / totalLeads) * 100).toFixed(1) : '0';

    // Chart 1: Leads generated by day (last 14 days)
    const last14DaysData = [];
    for (let i = 13; i >= 0; i--) {
      const d = subDays(now, i);
      const dayStr = format(d, 'MMM dd');
      const dStart = startOfDay(d);
      const dEnd = new Date(dStart.getTime() + 86400000);
      const count = allLeads.filter(
        (l) => new Date(l.createdAt) >= dStart && new Date(l.createdAt) < dEnd
      ).length;
      last14DaysData.push({ day: dayStr, count });
    }

    // Chart 2: Leads by state
    const stateMap: Record<string, number> = {};
    allLeads.forEach((l) => {
      stateMap[l.state] = (stateMap[l.state] || 0) + 1;
    });
    const leadsByState = Object.entries(stateMap).map(([state, count]) => ({ state, count }));

    // Chart 3: Leads by temperature
    const leadsByTemperature = [
      { temperature: 'HOT', count: hotLeads },
      { temperature: 'WARM', count: warmLeads },
      { temperature: 'COLD', count: coldLeads },
    ];

    // Chart 4: Leads by status
    const statusMap: Record<string, number> = {};
    allLeads.forEach((l) => {
      statusMap[l.status] = (statusMap[l.status] || 0) + 1;
    });
    const leadsByStatus = Object.entries(statusMap).map(([status, count]) => ({ status, count }));

    // Chart 5: Leads by city (Top 10)
    const cityMap: Record<string, number> = {};
    allLeads.forEach((l) => {
      const key = `${l.city}, ${l.state}`;
      cityMap[key] = (cityMap[key] || 0) + 1;
    });
    const leadsByCity = Object.entries(cityMap)
      .map(([city, count]) => ({ city, count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 10);

    // Leader Distribution
    const leaderMap: Record<string, number> = {};
    allLeads.forEach((l) => {
      const leaderName = l.assignedTo?.name || 'Unassigned';
      leaderMap[leaderName] = (leaderMap[leaderName] || 0) + 1;
    });
    const leadsByLeader = Object.entries(leaderMap).map(([leader, count]) => ({ leader, count }));

    return NextResponse.json({
      summary: {
        totalLeads,
        newLeads,
        hotLeads,
        warmLeads,
        coldLeads,
        unassignedLeads,
        assignedLeads,
        contactedLeads,
        interestedLeads,
        demoScheduled,
        demoCompleted,
        converted,
        lost,
        todaysNewLeads,
        thisWeeksLeads,
        thisMonthsLeads,
        rates: {
          contactRate,
          interestedRate,
          demoRate,
          conversionRate,
        },
      },
      charts: {
        last14DaysData,
        leadsByState,
        leadsByTemperature,
        leadsByStatus,
        leadsByCity,
        leadsByLeader,
      },
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
